#print("Hello World!")
print("Hello Again")
print("I like typing this.")
print("This is fun")
print("Yap!printing")
print("I'd much rather you 'not'.")
print('I"said"do not touch this.')
print("more")